### ISSUE TITLE
GBoF umbrella site

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#58]
- [ ] The main site will pull data from signature/selected Core Data projects
- [ ] In addition to the course template, there will be a "Featured Projects" section under "About"
- [ ] Navigation should have an overview map and links to the following pages: About Us and Resources
- [ ] Link to page content here: https://docs.google.com/document/d/1xtHicUm4LZCRCqczPyWQNpBefNzMcKeBqPf0Mq8BBnY/edit
